### ISSUE TITLE
Updates jets module for UL Production

### ISSUE THREAD

**Issue by SiewYan** [SiewYan/LatinoAnalysis#1]
## Tracking progress of jets module upgrade for UL Production
- uses CMSSW_10_6_27 for troubleshooting
- UL-Production branch
- all years affected, focuses 17,18 for now
- FatJet, correction, cleaning, systematics modules
- both for MC and Data:
  | Year | MC Production | Data Production |
  | ------ | ----- | ------ |
  | 2016 HIPM | [Summer20UL16_106x_nAODv8_HIPM_Full2016v8](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L787-L795) | [Run2016_UL2016_nAODv9_HIPM_Full2016v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L612-L618) |
  | 2016 noHIPM | [Summer20UL16_106x_nAODv8_noHIPM_Full2016v8](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L797-L805) | [Run2016_UL2016_nAODv9_noHIPM_Full2016v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L620-L627) |
  | 2017 | [Summer20UL17_106x_nAODv9_Full2017v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L808-L816) | [Run2017_UL2017_nAODv9_Full2017v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L630-L636)|
  | 2018 | [Summer20UL18_106x_nAODv9_Full2018v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L819-L827) | [Run2018_UL2018_nAODv9_Full2018v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L638-L645) |
 - JEC in Run2:
   | Year | Jet-Type | GT | Remark |
   | ------ | ------ | ----- | ------ |
   | 2016 APV | CHS and PUPPI (AK4 and AK8) | [106X_mcRun2_asymptotic_preVFP_v11](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL16APV_V7_MC.tar.gz?raw=true) |  |
   | 2016 noAPV | CHS and PUPPI (AK4 and AK8) | [106X_mcRun2_asymptotic_v17](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL16_V7_MC.tar.gz?raw=true) | |
   | 2017 | AK4PFCHS, AK4PFPuppi | [106X_mc2017_realistic_v8](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL17_V5_MC.tar.gz?raw=true) | JEC based on 106X __Summer19UL17__ (compatible with __Summer20UL17__) |
   | 2018 | CHS and Puppi (AK4 and AK8) | [106X_upgrade2018_realistic_v15_L1v1](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL18_V5_MC.tar.gz?raw=true) | JEC based on 106X __Summer19UL18__ (compatible with __Summer20UL18__)  |
   * https://twiki.cern.ch/twiki/bin/viewauth/CMS/JECDataMC#Recommended_for_MC
   * https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/2131/1.html
 - JR Run2:
   | Year | SF Data | SF MC | Remarks |
   | ------ | ------ | ----- | ------ |
   | 2016 APV | | |
   | 2016 noAPV | | |
   | 2017 | [Summer19UL17_JRV2_DATA](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL17_JRV2_DATA.tar.gz) | [Summer19UL17_JRV2_MC](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL17_JRV2_MC.tar.gz) | they are NOT in a Pt-dependent format, the previously strong pt dependency at high eta is however observed to be reduced in UL |
   | 2018 | [Summer19UL18_JRV2_DATA](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL18_JRV2_DATA.tar.gz?raw=true) | [Summer19UL18_JRV2_MC](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL18_JRV2_MC.tar.gz?raw=true) | they are NOT in a Pt-dependent format, the previously strong pt dependency at high eta is however observed to be reduced in UL |
 
   * https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution#2016_data
 - PUID: https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetIDUL 
 - JetID: https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1
 - affected modules (taken from [steps_cfg.py](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L1028-L1034)):
   - [FatJetCorrHelper](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2855-L2862)  
   - CorrFatJetMC
   - CleanFatJet
### to-do list:
 - [ ] troubleshoot Fatjet maker:
   - [ ] Cross cleaning FatJet and lepton; CleanedFatJet and CleanedJet
   - [ ] Fatjet ID : https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1    ( https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetIDUL#Recommendations_for_2018_UL_data)
   - [ ] Kineamtic cut 
 - [ ] updating JetID, PU etc

Source: [google doc](https://docs.google.com/document/d/1zu6VMU6mDbEqq3a2CVoH_Q0G26YiZYIvjKxpc94KQvw/edit#)

**Comment by SiewYan** [comment]
move to https://github.com/mpresill/LatinoAnalysis/issues/2
